apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: root-app
    app.kubernetes.io/part-of: gitops-platform
spec:
  project: default

  source:
    repoURL: https://github.com/mmathank26/devops-eks-gitops
    targetRevision: HEAD
    # Points to the folder containing all child ArgoCD Application manifests
    path: argocd-apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true       # Remove resources deleted from Git
      selfHeal: true    # Revert manual changes made directly in cluster
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
